-- BUG-027: Persisted cheating_violations rows are the source of truth.
-- `event_id` is generated by the browser and makes retrying the same event safe.
ALTER TABLE cheating_violations
  ADD COLUMN IF NOT EXISTS event_id text;

CREATE UNIQUE INDEX IF NOT EXISTS cheating_violations_attempt_event_id_unique
  ON cheating_violations (quiz_attempt_id, event_id)
  WHERE event_id IS NOT NULL;

-- These columns are a cached summary only. Event detail remains in
-- cheating_violations and must never be reconstructed from client input.
ALTER TABLE quiz_attempts
  ADD COLUMN IF NOT EXISTS violation_count integer NOT NULL DEFAULT 0;

ALTER TABLE quiz_attempts
  ADD COLUMN IF NOT EXISTS violations jsonb NOT NULL DEFAULT '[]'::jsonb;

-- Rollback (only after confirming no clients depend on idempotent retries):
-- DROP INDEX IF EXISTS cheating_violations_attempt_event_id_unique;
-- ALTER TABLE cheating_violations DROP COLUMN IF EXISTS event_id;
